Sql arpad dev
BiblioLexicus/BiblioBackend pull request #9
Opened 2022-02-18 01:35 UTC by Arpad05

Ceci devrait être le modèle fonctionnel finale avec tout les éléments de bases tel que discuté.

Je demande l'aprobation totale et complète de tout le monde pour qu'on soit tous d'accord avec la base de données et pour éviter les "surpises".

2022-02-18 02:02 UTC, BBArikL requested changes
Ok so:
- On a vérifié que cela fonctionne bien?

- Notre description de fichier sql correspond bien au fichier en tant que tel?

Pour moi c'est d'accord, on peut même garder la version 4 au cas où. On pourrait aussi bouger le fichier sql + le fichier explicatif dans dbconfig/, sinon je ne suis personne pour juger de la qualité du sql code. 

Aussi @xelorax ne mets jamais de mots de passe ou d'informations de DB sur un repo public ( voir https://github.com/BiblioLexicus/BiblioBackend/commit/8781fb71da14d007166ce70a639290b59b1690e2 ) tu vas devoir renouveler les informations et tu enverras en privé les informations de connexion (si on utilise toujours ce provider, sinon tu peux seulement enlever le fichier et annuler avec le provider).

2022-02-18 23:09 UTC, BBArikL commented
Puisque @Arpad05 m'a confirmé que cela fonctionne, je vais juste bouger les fichiers dans le dossier dbconfig et enlever le fichier de @xelorax .

2022-02-18 23:16 UTC, BBArikL approved these changes

2022-02-18 23:36 UTC, yassine128 approved these changes

2022-02-19 02:19 UTC, xelorax commented
> Ok so:
> 
> * On a vérifié que cela fonctionne bien?
> * Notre description de fichier sql correspond bien au fichier en tant que tel?
> 
> Pour moi c'est d'accord, on peut même garder la version 4 au cas où. On pourrait aussi bouger le fichier sql + le fichier explicatif dans dbconfig/, sinon je ne suis personne pour juger de la qualité du sql code.
> 
> Aussi @xelorax ne mets jamais de mots de passe ou d'informations de DB sur un repo public ( voir [8781fb7](https://github.com/BiblioLexicus/BiblioBackend/commit/8781fb71da14d007166ce70a639290b59b1690e2) ) tu vas devoir renouveler les informations et tu enverras en privé les informations de connexion (si on utilise toujours ce provider, sinon tu peux seulement enlever le fichier et annuler avec le provider).

Merci... Bon point j'avais oublié que c'étais public

2022-02-19 02:25 UTC, xelorax approved these changes
Ça a l'air bon... as-t'on besoin du hash du password des utilisateurs? ou on skip le password? au pire c pas si pire d'ajouter une colonne dans du sql

2022-02-19 02:53 UTC, BBArikL commented
Ah c'est vrai! On le rajoute puis cela devrait être bon.... je crois

2022-02-19 03:05 UTC, BBArikL commented
Alright, merging

2022-02-19 03:05 UTC, merged